# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-24 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lhs', models.TextField()),
                ('rhs', models.TextField()),
                ('operator', models.PositiveIntegerField(choices=[(4, '=='), (5, '!='), (6, '>'), (7, '<'), (8, '>='), (9, '<=')], default=4)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.PositiveIntegerField(choices=[(1, 'AND'), (2, 'OR'), (3, 'XOR')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='RPiPin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.SmallIntegerField()),
                ('label', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'RPi Pin',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rpipin',
            unique_together=set([('pin', 'label')]),
        ),
        migrations.AddField(
            model_name='condition',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='veggy_pi.ConditionGroup'),
        ),
    ]
