# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-24 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veggy_pi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RPiPin',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.AlterField(
            model_name='condition',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='veggy_pi.ConditionGroup'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='lhs',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='condition',
            name='rhs',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='conditiongroup',
            name='operator',
            field=models.PositiveIntegerField(choices=[(1, 'AND'), (2, 'OR')], default=1),
        ),
    ]
